name: Build Cloud Resume Challenge App
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Build-Cloud-Resume-Challenge-App:
    runs-on: ubuntu-latest
    environment: development
    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.4
    - name: Initialize terraform
      run: terraform init -backend-config="access_key=$AWS_ACCESS_KEY_ID" -backend-config="secret_key=$AWS_SECRET_ACCESS_KEY"
      working-directory: ./infra/app
    - name: Plan terraform
      run: terraform plan
      working-directory: ./infra/app