
name: Build Cloud Resume Challenge App
run-name: ${{ github.actor }} is deploying a development Cloud Resume Challenge.
on: [pull_request]
jobs:
  Build-Cloud-Resume-Challenge-App:
    runs-on: ubuntu-latest
    environment: development
    env:
      AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.4
    - run: echo ${{github.event.number}}
    - name: Initialize terraform
      run: terraform init -backend-config="key=${{github.event.number}}"
      working-directory: ./infra/app
    - name: Apply terraform
      run: terraform apply -auto-approve
      working-directory: ./infra/app