name: Deploy Cloud Resume Challenge App
run-name: ${{ github.actor }} is deploying a development Cloud Resume Challenge.
on: [pull_request]
jobs:
  Build-Cloud-Resume-Challenge-App:
    runs-on: ubuntu-latest
    environment: development
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.4
      - uses: actions/setup-node@v3
        with:
          node-version: 18.13.0
      - name: Initialize app terraform
        run: terraform init -backend-config="key=${{github.event.number}}-app"
        working-directory: ./infra/app
      - name: Apply app terraform
        run: terraform apply -auto-approve
        working-directory: ./infra/app
      - name: Set app terraform outputs
        run: |
          echo "PROJECT=$(terraform output -raw project)" >> "$GITHUB_ENV" && 
          echo "REACT_APP_API_BASE_URL=$(terraform output -raw app_url)" >> "$GITHUB_ENV"
        working-directory: ./infra/app
      - name: Install web dependencies
        run: npm install
      - run: echo ${{ env.REACT_APP_API_BASE_URL }}
      - name: Build web
        run: |
          export REACT_APP_API_BASE_URL=${{ env.REACT_APP_API_BASE_URL }} && 
          npm run build --workspace=web
      - name: Initialize web terraform
        run: terraform init -backend-config="key=${{github.event.number}}-web"
        working-directory: ./infra/web
      - run: echo ${{ env.PROJECT }}
      - name: Apply web terraform
        run: terraform apply -var="project=${{ env.PROJECT }}" -auto-approve
        working-directory: ./infra/web
