name: Deploy Cloud Resume Challenge
run-name: ${{ github.actor }} is deploying a development Cloud Resume Challenge.
on: [pull_request]
jobs:
  deploy:
    uses: ./.github/workflows/deploy-cloud-resume-challenge.yml
    with:
      backend-key: ${{ github.event.number }}
      backend-bucket: jlawcordova-cloud-resume-challenge-tf-backend-development
      target-environment: development
    secrets: inherit
