name: Deploy Cloud Resume Challenge Production
run-name: ${{ github.actor }} is deploying Cloud Resume Challenge in production.
on:
  push:
    branches:
      - "main"
jobs:
  deploy:
    uses: ./.github/workflows/deploy-cloud-resume-challenge.yml
    with:
      backend-key: main
      backend-bucket: jlawcordova-cloud-resume-challenge-tf-backend
      target-environment: production
    secrets: inherit

  test:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.13.0
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          working-directory: ./test
