name: Deploy Cloud Resume Challenge
run-name: ${{ github.actor }} is deploying Cloud Resume Challenge.
on:
  workflow_call:
    inputs:
      backend-key:
        required: true
        type: string
      backend-bucket:
        required: true
        type: string
      target-environment:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
jobs:
  deploy-app:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target-environment }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_project: ${{ vars.TF_VAR_PROJECT }}
      TF_VAR_domain: ${{ vars.TF_VAR_APP_DOMAIN }}
      TF_VAR_alarm_email: ${{ vars.TF_VAR_ALARM_EMAIL }}
      TF_VAR_environment: ${{ inputs.target-environment }}
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.4
          terraform_wrapper: false
      - uses: actions/setup-node@v3
        with:
          node-version: 18.13.0
      - name: Initialize app terraform
        run: |
          terraform init \
            -backend-config="key=${{ inputs.backend-key }}-app" \
            -backend-config="bucket=${{ inputs.backend-bucket }}"
        working-directory: ./infra/app
      - name: Apply app terraform
        run: terraform apply -auto-approve
        working-directory: ./infra/app
      - id: app-output
        name: Set app terraform outputs
        run: |
          echo "project=$(terraform output -raw project)" >> "$GITHUB_OUTPUT" && 
          echo "app-url=$(terraform output -raw app_url)" >> "$GITHUB_OUTPUT"
        working-directory: ./infra/app
    outputs:
      project: ${{ steps.app-output.outputs.project }}
      app-url: ${{ steps.app-output.outputs.app-url }}

  build-web:
    needs: deploy-app
    runs-on: ubuntu-latest
    environment: ${{ inputs.target-environment }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REACT_APP_API_BASE_URL: ${{needs.deploy-app.outputs.app-url}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.13.0
      - name: Install web dependencies
        run: npm install
      - name: Lint web
        run: npm run lint --workspace=web
      - name: Build web
        run: npm run build --workspace=web
      - name: Archive web artifact
        uses: actions/upload-artifact@v3
        with:
          name: web-build
          path: web/build

  deploy-web:
    needs: [deploy-app, build-web]
    runs-on: ubuntu-latest
    environment: ${{ inputs.target-environment }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_project: ${{needs.deploy-app.outputs.project}}
      TF_VAR_domain: ${{ vars.TF_VAR_WEB_DOMAIN }}
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.4
          terraform_wrapper: false
      - name: Download web artifact
        uses: actions/download-artifact@v3
        with:
          name: web-build
          path: web/build
      - name: Initialize web terraform
        run: |
          terraform init \
            -backend-config="key=${{ inputs.backend-key }}-web" \
            -backend-config="bucket=${{ inputs.backend-bucket }}"
        working-directory: ./infra/web
      - name: Apply web terraform
        run: terraform apply -auto-approve
        working-directory: ./infra/web
      - id: web-output
        name: Set web terraform outputs
        run: |
          echo "web-url=$(terraform output -raw web_url)" >> "$GITHUB_OUTPUT"
        working-directory: ./infra/app

  test:
    needs: [deploy-app, deploy-web]
    runs-on: ubuntu-latest
    env:
      CYPRESS_BASE_URL: ${{needs.deploy-web.outputs.web-url}}
      CYPRESS_API_URL: ${{needs.deploy-app.outputs.app-url}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.13.0
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          working-directory: ./test

